export const MOCK_GRADUATES = [
  {
    id: 'grad-1',
    name: 'Thabo Nkosi',
    email: 'thabo@demo.vantage.co.za',
    role: 'GRADUATE',
    aptitudeScore: 82,
    vps: 91,
    location: 'Johannesburg, GP',
    university: 'University of the Witwatersrand',
    degree: 'BSc Computer Science',
    graduationYear: 2023,
    bio: 'Passionate software developer with a strong foundation in algorithms and data structures. Eager to solve real-world problems through clean, scalable code.',
    avatar: null,
    skills: [
      { id: 's1', name: 'JavaScript', isVerified: true, proofHash: 'a3f8c2d1e9b4f7a0c6d3e8b2f5a9c1d4' },
      { id: 's2', name: 'React', isVerified: true, proofHash: 'b7e1f4a8d2c5f0e3a6b9d4c7f2e5a8b1' },
      { id: 's3', name: 'Node.js', isVerified: true, proofHash: 'c4d7e0f3a6b9c2d5e8f1a4b7c0d3e6f9' },
      { id: 's4', name: 'TypeScript', isVerified: true, proofHash: 'd1e4f7a0b3c6d9e2f5a8b1c4d7e0f3a6' },
      { id: 's5', name: 'PostgreSQL', isVerified: false, proofHash: null },
      { id: 's6', name: 'Python', isVerified: false, proofHash: null },
    ],
    cvSummary: {
      education: 'BSc Computer Science — University of the Witwatersrand (2020–2023)',
      experience: [
        'Software Engineering Intern — FNB Digital (Jan 2023 – Jun 2023)',
        'Freelance Web Developer — Self-employed (2021–2022)',
      ],
      certifications: ['AWS Cloud Practitioner', 'freeCodeCamp JavaScript Algorithms'],
      languages: ['English (Fluent)', 'Zulu (Native)', 'Sotho (Conversational)'],
    },
    challenges: [
      { taskId: 'task-1', title: 'Logic Puzzle Set A', completed: true, score: 95 },
      { taskId: 'task-2', title: 'React Component Build', completed: true, score: 88 },
      { taskId: 'task-3', title: 'SQL Query Challenge', completed: false, score: null },
      { taskId: 'task-4', title: 'Algorithm Optimisation', completed: false, score: null },
    ],
  },
  {
    id: 'grad-2',
    name: 'Naledi Dlamini',
    email: 'naledi@demo.vantage.co.za',
    role: 'GRADUATE',
    aptitudeScore: 74,
    vps: 72,
    location: 'Cape Town, WC',
    university: 'University of Cape Town',
    degree: 'BCom Information Systems',
    graduationYear: 2023,
    bio: 'Detail-oriented information systems graduate with hands-on experience in data analysis and business process automation.',
    avatar: null,
    skills: [
      { id: 's7', name: 'Excel & Power BI', isVerified: true, proofHash: 'e8f1a4b7c0d3e6f9a2b5c8d1e4f7a0b3' },
      { id: 's8', name: 'SQL', isVerified: true, proofHash: 'f5a8b1c4d7e0f3a6b9c2d5e8f1a4b7c0' },
      { id: 's9', name: 'Python', isVerified: false, proofHash: null },
      { id: 's10', name: 'Tableau', isVerified: false, proofHash: null },
      { id: 's11', name: 'Business Analysis', isVerified: false, proofHash: null },
    ],
    cvSummary: {
      education: 'BCom Information Systems — University of Cape Town (2020–2023)',
      experience: [
        'Data Analyst Intern — Standard Bank (Jun 2022 – Dec 2022)',
      ],
      certifications: ['Google Data Analytics Certificate', 'Microsoft Power BI Desktop'],
      languages: ['English (Fluent)', 'Xhosa (Native)'],
    },
    challenges: [
      { taskId: 'task-1', title: 'Logic Puzzle Set A', completed: true, score: 78 },
      { taskId: 'task-2', title: 'React Component Build', completed: false, score: null },
      { taskId: 'task-3', title: 'SQL Query Challenge', completed: true, score: 91 },
      { taskId: 'task-4', title: 'Algorithm Optimisation', completed: false, score: null },
    ],
  },
  {
    id: 'grad-3',
    name: 'Sipho Mokoena',
    email: 'sipho@demo.vantage.co.za',
    role: 'GRADUATE',
    aptitudeScore: 68,
    vps: 61,
    location: 'Durban, KZN',
    university: 'Durban University of Technology',
    degree: 'BTech Software Development',
    graduationYear: 2022,
    bio: 'Software development graduate with a keen interest in mobile applications and UI/UX design. Committed to building inclusive digital products.',
    avatar: null,
    skills: [
      { id: 's12', name: 'Flutter', isVerified: true, proofHash: 'a9b2c5d8e1f4a7b0c3d6e9f2a5b8c1d4' },
      { id: 's13', name: 'Dart', isVerified: false, proofHash: null },
      { id: 's14', name: 'Figma', isVerified: false, proofHash: null },
      { id: 's15', name: 'Java', isVerified: false, proofHash: null },
      { id: 's16', name: 'Firebase', isVerified: false, proofHash: null },
    ],
    cvSummary: {
      education: 'BTech Software Development — Durban University of Technology (2019–2022)',
      experience: [
        'Junior Mobile Developer — Vodacom (Mar 2022 – Sep 2022)',
      ],
      certifications: ['Google Associate Android Developer'],
      languages: ['English (Fluent)', 'Zulu (Native)'],
    },
    challenges: [
      { taskId: 'task-1', title: 'Logic Puzzle Set A', completed: true, score: 71 },
      { taskId: 'task-2', title: 'React Component Build', completed: false, score: null },
      { taskId: 'task-3', title: 'SQL Query Challenge', completed: false, score: null },
      { taskId: 'task-4', title: 'Algorithm Optimisation', completed: false, score: null },
    ],
  },
];

export const MOCK_EMPLOYER = {
  id: 'emp-1',
  name: 'Acme Corp',
  email: 'employer@demo.vantage.co.za',
  role: 'EMPLOYER',
  industry: 'Financial Technology',
  location: 'Sandton, GP',
  description: 'Leading South African fintech company building the next generation of payment infrastructure.',
  openRoles: ['Junior Software Engineer', 'Data Analyst', 'Mobile Developer'],
};

export const MOCK_CHALLENGES = [
  {
    taskId: 'task-1',
    title: 'Logic Puzzle Set A',
    description: 'Solve a series of 10 logical reasoning problems that test pattern recognition, deductive reasoning, and abstract thinking. Each problem has one correct answer.',
    skill: 'Logical Reasoning',
    difficulty: 'Medium',
    timeLimit: 20,
    points: 100,
  },
  {
    taskId: 'task-2',
    title: 'React Component Build',
    description: 'Build a functional React component from a given spec. You will receive a design brief and must produce working JSX with correct state management and props.',
    skill: 'React',
    difficulty: 'Hard',
    timeLimit: 30,
    points: 150,
  },
  {
    taskId: 'task-3',
    title: 'SQL Query Challenge',
    description: 'Write SQL queries to answer 5 business questions from a given schema. Queries are evaluated for correctness and efficiency.',
    skill: 'SQL',
    difficulty: 'Medium',
    timeLimit: 25,
    points: 120,
  },
  {
    taskId: 'task-4',
    title: 'Algorithm Optimisation',
    description: 'Given an inefficient algorithm, refactor it to reduce time complexity. Your solution will be tested against large inputs.',
    skill: 'Algorithms',
    difficulty: 'Hard',
    timeLimit: 35,
    points: 200,
  },
];

export const MOCK_ROI_DEFAULTS = {
  avgSalary: 420000,
  hiringCost: 85000,
  timeToHire: 45,
  retentionRate: 78,
  vantageRetentionBoost: 22,
  vantageTimeToHireSaving: 18,
};

